const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info:{
        version: "0.1.0",
        title:"Movie Rest API with Swagger",
        description:"Documentation generated by the <b><i>swagger-autogen</i></b> module"
    },
    host:"localhost:3000",
    basePath:"/",
    schemes:["http", "https"],
    consumes:["application.json"],
    produces:["application.json"],
    tags:[
        {
            "name":"Movie",
            "description":"Movies information"
        },
        {
            "name":"Rent",
            "description":"Information of rented movies"
        }
    ],

    definitions:{
        Movie:{
            "id": 10002,
            "name": "lord of the rings",
            "year": "1999",
            "genre": "adventure",
            "income": 5498700
        },
        Movies:[
            { $ref: "#/definitions/Movie" }
        ],
        Rent:{
            "movieId": 10002,
            "duration": 10,
            "person": "Hi Coders"
        },
        Rents:[
            { $ref: "#/definitions/Rent" }
        ]
    }
}



const outputFile = './swagger.json';
const endpointsFile = ['./app.js'];

swaggerAutogen(outputFile, endpointsFile, doc).then(()=>{
    require('./app');
})